version: '3.8'
services:
  backend:
    container_name: admin-service_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
    depends_on:
      - db
  db:
    container_name: admin-service_db
    image: mysql:5.7.22
    restart: on-failure
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
